# List all recipes
list:
    just --list

# Run unit tests
test:
    go test ./...

# Run static checks
lint:
    test -z "$(gofmt -l .)"
    go vet ./...

# Generate OpenAPI types
typegen:
    oapi-codegen -config oapi-codegen.yaml ../openapi/treasury.yaml
